description = "Chandler's blog about programming, languages, compilers, performance, cpus, tech, and everything else."
keywords = [
  'programming',
  'coding',
  'languages',
  'programming languages',
  'compilers',
  'performance',
  'cpus',
  'tech',
]

defaultTheme = "dark"
disableThemeToggle = true

ShowShareButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
ShowBreadCrumbs = false
hideFooter = true

#[label]
#text = "Home"

[homeInfoParams]
  Content = "A blog about programming, languages, compilers, optimization, performance, CPUs, technology, and everything else. Why use 50 words when 500 will do. =D"

[[socialIcons]]
name = "mastodon"
url = "https://hachyderm.io/@chandlerc"

[[socialIcons]]
name = "github"
url = "https://github.com/chandlerc"

[[socialIcons]]
name = "twitter"
url = "https://twitter.com/chandlerc1024"
