[[mounts]]
  source = 'static'
  target = 'static'

[[mounts]]
  source = 'LICENSE.md'
  target = 'static/LICENSE.md'

[[mounts]]
  source = 'assets'
  target = 'assets'

[[mounts]]
  source = 'layouts'
  target = 'layouts'

[[mounts]]
  source = 'third_party/highlight.js/assets/css'
  target = 'assets/hljs/css'

[[mounts]]
  source = 'third_party/highlight.js/assets/js'
  target = 'assets/hljs/js'

[[mounts]]
  source = 'third_party/carbon-lang/assets/js'
  target = 'assets/carbon-lang/js'

[[mounts]]
  source = 'third_party/iosevka/layouts/partials'
  target = 'layouts/partials/iosevka'

[[mounts]]
  source = 'third_party/iosevka/static/fonts'
  target = 'assets/fonts/iosevka'

[[mounts]]
  source = 'third_party/open_sans'
  target = 'assets/fonts/open_sans'
  includeFiles = '*.woff2'

[[mounts]]
  source = 'third_party/montserrat'
  target = 'assets/fonts/montserrat'
  includeFiles = '*.woff2'

[[mounts]]
  source = '/dev/null'
  target = 'static/highlight-js'

[[mounts]]
  source = '/dev/null'
  target = 'static/reveal-js/dist/theme'

[[mounts]]
  source = '/dev/null'
  target = 'static/reveal-js/plugin/highlight'

[[mounts]]
  source = '/dev/null'
  target = 'static/reveal-hugo/themes'
